const API_BASE = "/api/stocks";
const GROUPS = [
    { title: "Valuation", metrics: [["pe","P/E","ratio"],["forward_pe","Forward P/E","ratio"],["pb","Price / Book","ratio"],["ps","Price / Sales","ratio"],["peg","PEG","ratio"],["ev_ebitda","EV / EBITDA","ratio"],["ev_revenue","EV / Revenue","ratio"],["dividend_yield","Dividend Yield","percent"],["payout_ratio","Payout Ratio","percent"]] },
    { title: "Profitability", metrics: [["roe","ROE","percent"],["roa","ROA","percent"],["gross_margin","Gross Margin","percent"],["operating_margin","Operating Margin","percent"],["profit_margin","Net Margin","percent"]] },
    { title: "Financial Health", metrics: [["debt_equity","Debt / Equity","ratio"],["current_ratio","Current Ratio","ratio"],["quick_ratio","Quick Ratio","ratio"],["beta","Beta","number"]] },
    { title: "Growth", metrics: [["revenue_growth","Revenue Growth","percent"],["profit_growth","Profit Growth","percent"],["eps_growth","EPS Growth","percent"],["revenue_cagr_3y","Revenue CAGR 3Y","percent_decimal"],["revenue_cagr_5y","Revenue CAGR 5Y","percent_decimal"],["profit_cagr_3y","Profit CAGR 3Y","percent_decimal"],["profit_cagr_5y","Profit CAGR 5Y","percent_decimal"],["eps_cagr_3y","EPS CAGR 3Y","percent_decimal"],["eps_cagr_5y","EPS CAGR 5Y","percent_decimal"],["fcf_cagr_3y","FCF CAGR 3Y","percent_decimal"],["fcf_cagr_5y","FCF CAGR 5Y","percent_decimal"],["operating_margin_change","Operating Margin Change","pp"]] }
];
let financialDisplayMode = "international";
let selectedStock = null;

function esc(value) { return String(value ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); }
function fmtNumber(value, digits=2) { return Number(value).toLocaleString("en-IN", {maximumFractionDigits:digits, minimumFractionDigits:0}); }
function fmtPercent(value, multiplier=1) { return value == null || !Number.isFinite(Number(value)) ? "—" : `${fmtNumber(Number(value)*multiplier,2)}%`; }
function fmtRatio(value) { return value == null || !Number.isFinite(Number(value)) ? "—" : `${fmtNumber(Number(value),2)}x`; }
function fmtCompact(value,currency="") {
    if (value == null || !Number.isFinite(Number(value))) return "—";
    const n=Number(value), p=currency==="INR"?"₹":currency==="USD"?"$":currency?`${currency} `:"", a=Math.abs(n);
    if(a>=1e12)return `${p}${fmtNumber(n/1e12,2)}T`; if(a>=1e9)return `${p}${fmtNumber(n/1e9,2)}B`; if(a>=1e6)return `${p}${fmtNumber(n/1e6,2)}M`; if(a>=1e3)return `${p}${fmtNumber(n/1e3,2)}K`; return `${p}${fmtNumber(n,2)}`;
}
function fmtFinancial(value,currency="") { if(value==null||!Number.isFinite(Number(value)))return "—"; if(financialDisplayMode==="indian"&&currency==="INR")return `₹${fmtNumber(Number(value)/1e7,2)} Cr`; return fmtCompact(value,currency); }
function fmtPrice(value,currency="") { if(value==null||!Number.isFinite(Number(value)))return "—"; const p=currency==="INR"?"₹":currency==="USD"?"$":currency?`${currency} `:""; return `${p}${fmtNumber(Number(value),2)}`; }
function valueForMetric(key,value,type) { if(value==null)return "—"; if(type==="percent")return fmtPercent(value); if(type==="percent_decimal")return fmtPercent(value,100); if(type==="ratio")return fmtRatio(value); if(type==="pp")return `${fmtNumber(Number(value),2)} pp`; if(type==="text")return String(value); return fmtNumber(Number(value),2); }
function metricCard(key,label,value,type) { const display=valueForMetric(key,value,type); const cls=Number(value)>0&&(type==="percent"||type==="percent_decimal"||type==="pp")?"metric-positive":Number(value)<0&&(type==="percent"||type==="percent_decimal"||type==="pp")?"metric-negative":""; return `<div class="stock-metric-card"><span class="stock-metric-label">${esc(label)}</span><strong class="stock-metric-value ${cls}">${esc(display)}</strong></div>`; }
function renderGroup(group,f) { return `<section class="stock-section"><div class="stock-section-header"><h2>${esc(group.title)}</h2></div><div class="stock-metrics-grid">${group.metrics.map(([k,l,t])=>metricCard(k,l,f[k],t)).join("")}</div></section>`; }
function renderCompany(f) { const c=f.currency||""; return `<section class="stock-hero"><div><div class="stock-eyebrow">${esc(f.exchange||"")} · ${esc(f.symbol||"")}</div><h1>${esc(f.name||f.symbol||"")}</h1><p>${esc(f.sector||"")}${f.industry?` · ${esc(f.industry)}`:""}${f.country?` · ${esc(f.country)}`:""}</p></div><div class="stock-price-block"><strong>${esc(fmtPrice(f.price,c))}</strong><span>${esc(c)}</span></div></section><section class="stock-summary-grid">${metricCard("market_cap","Market Cap",fmtFinancial(f.market_cap,c),"text")}${metricCard("enterprise_value","Enterprise Value",fmtFinancial(f.enterprise_value,c),"text")}${metricCard("revenue","Latest Revenue",fmtFinancial(f.revenue,c),"text")}${metricCard("net_profit","Latest Net Profit",fmtFinancial(f.net_profit,c),"text")}${metricCard("ebitda","Latest EBITDA",fmtFinancial(f.ebitda,c),"text")}${metricCard("free_cash_flow","Latest Free Cash Flow",fmtFinancial(f.free_cash_flow,c),"text")}</section>`; }
function formatStatementValue(field,value,currency) { if(value==null)return "—"; if(field.toLowerCase().includes("eps"))return fmtNumber(value,2); return fmtFinancial(value,currency); }
function statementTable(title,rows,currency) { if(!rows?.length)return `<section class="stock-section"><div class="stock-section-header"><h2>${esc(title)}</h2></div><div class="stock-no-data">No historical data available.</div></section>`; const fields=[...new Set(rows.flatMap(r=>Object.keys(r.values||{})))]; return `<section class="stock-section"><div class="stock-section-header"><h2>${esc(title)}</h2><span>Annual</span></div><div class="stock-table-wrap"><table class="stock-table"><thead><tr><th>Metric</th>${rows.map(r=>`<th>${esc(r.period.slice(0,4))}</th>`).join("")}</tr></thead><tbody>${fields.map(field=>`<tr><td>${esc(field.replace(/([a-z])([A-Z])/g,"$1 $2"))}</td>${rows.map(row=>`<td>${esc(formatStatementValue(field,row.values?.[field],currency))}</td>`).join("")}</tr>`).join("")}</tbody></table></div></section>`; }
function renderAnalysis(data,container) { const f=data.fundamentals||{}, indian=f.currency==="INR"; if(!indian)financialDisplayMode="international"; container.innerHTML=`${renderCompany(f)}${GROUPS.map(g=>renderGroup(g,f)).join("")}<section class="stock-section"><div class="stock-section-header"><h2>Financial Statements</h2><div class="stock-display-controls"><span>Display:</span><label class="stock-unit-toggle"><input type="radio" name="stock-financial-unit" value="international" ${financialDisplayMode==="international"?"checked":""}><span>B / T</span></label><label class="stock-unit-toggle ${indian?"":"disabled"}"><input type="radio" name="stock-financial-unit" value="indian" ${financialDisplayMode==="indian"?"checked":""} ${indian?"":"disabled"}><span>₹ Cr</span></label></div></div><div class="stock-statement-tabs"><button class="stock-tab active" data-tab="income">Income Statement</button><button class="stock-tab" data-tab="balance">Balance Sheet</button><button class="stock-tab" data-tab="cash">Cash Flow</button></div><div id="stock-statement-content">${statementTable("Income Statement",data.income_statement,f.currency||"")}</div></section><section class="stock-section stock-warnings"><div class="stock-section-header"><h2>Data Notes</h2></div><ul>${(data.warnings||[]).map(w=>`<li>${esc(w)}</li>`).join("")}</ul><small>Data as of ${esc(f.data_as_of||"—")} · Source: ${esc(f.source||"Yahoo Finance")}</small></section>`;
    const content=document.getElementById("stock-statement-content"); container.querySelectorAll(".stock-tab").forEach(tab=>tab.addEventListener("click",()=>{container.querySelectorAll(".stock-tab").forEach(t=>t.classList.remove("active"));tab.classList.add("active");const k=tab.dataset.tab;if(k==="income")content.innerHTML=statementTable("Income Statement",data.income_statement,f.currency||"");if(k==="balance")content.innerHTML=statementTable("Balance Sheet",data.balance_sheet,f.currency||"");if(k==="cash")content.innerHTML=statementTable("Cash Flow",data.cash_flow,f.currency||"");}));
    container.querySelectorAll('input[name="stock-financial-unit"]').forEach(input=>input.addEventListener("change",()=>{financialDisplayMode=input.value;renderAnalysis(data,container);}));
}
async function loadStock(symbol,container,status) { status.textContent=`Loading ${symbol}…`;container.innerHTML=`<div class="stock-loading">Loading ${esc(symbol)} fundamentals…</div>`;try{const r=await fetch(`${API_BASE}/${encodeURIComponent(symbol)}`,{headers:{Accept:"application/json"}});const data=await r.json();if(!r.ok)throw new Error(data?.detail||`HTTP ${r.status}`);renderAnalysis(data,container);status.textContent="";}catch(e){container.innerHTML=`<div class="stock-error"><h2>Unable to load ${esc(symbol)}</h2><p>${esc(e.message)}</p></div>`;status.textContent="";}}

function selectionFilters() {
    return { sector: document.getElementById("stock-sector").value, query: document.getElementById("stock-filter-search").value.trim(),
        min_market_cap_cr: document.getElementById("stock-min-mcap").value, max_market_cap_cr: document.getElementById("stock-max-mcap").value,
        min_pe: document.getElementById("stock-min-pe").value, max_pe: document.getElementById("stock-max-pe").value,
        min_roe: document.getElementById("stock-min-roe").value, max_roe: document.getElementById("stock-max-roe").value };
}
function queryString(filters) { const p=new URLSearchParams(); Object.entries(filters).forEach(([k,v])=>{if(v!==""&&v!=null)p.set(k,v);}); return p.toString(); }
function renderSelection(data,screen) {
    const filters=selectionFilters();
    const sectors=(data.sectors||[]).map(s=>`<option value="${esc(s)}" ${s===filters.sector?"selected":""}>${esc(s)}</option>`).join("");
    const rows=(data.stocks||[]).map(s=>`<div class="stock-picker-row ${selectedStock?.symbol===s.symbol?"selected":""}" data-symbol="${esc(s.symbol)}"><div><strong>${esc(s.name)}</strong><small>${esc(s.symbol)}</small></div><div class="stock-picker-metrics"><span>Market Cap <b>${s.market_cap_cr==null?"—":`₹${fmtNumber(s.market_cap_cr,0)} Cr`}</b></span><span>P/E <b>${s.pe==null?"—":`${fmtNumber(s.pe,2)}x`}</b></span><span>ROE <b>${s.roe==null?"—":`${fmtNumber(s.roe,2)}%`}</b></span></div><button class="stock-select-btn" type="button">${selectedStock?.symbol===s.symbol?"Selected":"Select"}</button></div>`).join("");
    screen.innerHTML=`<div class="stock-selection-layout"><aside class="stock-selected-panel"><div class="stock-selection-kicker">SELECTED STOCK</div>${selectedStock?`<div class="stock-selected-card"><strong>${esc(selectedStock.name)}</strong><small>${esc(selectedStock.symbol)}</small><span>${esc(selectedStock.sector||"")}</span></div>`:`<div class="stock-no-selection">No stock selected</div>`}<button id="stock-analyze-selected" class="stock-analyze-btn" type="button" ${selectedStock?"":"disabled"}>Analyze Stock</button><small>${selectedStock?"One stock selected.":"Select one stock from the list."}</small></aside><section class="stock-picker-panel"><div class="stock-picker-filters"><label>SECTOR<select id="stock-sector"><option value="">Select sector</option>${sectors}</select></label><label>SEARCH<input id="stock-filter-search" value="${esc(filters.query)}" placeholder="Search company or symbol…"></label><label>MARKET CAP MIN<input id="stock-min-mcap" type="number" min="0" value="${esc(filters.min_market_cap_cr)}" placeholder="₹ Cr"></label><label>MARKET CAP MAX<input id="stock-max-mcap" type="number" min="0" value="${esc(filters.max_market_cap_cr)}" placeholder="₹ Cr"></label><label>P/E MIN<input id="stock-min-pe" type="number" min="0" step="0.1" value="${esc(filters.min_pe)}"></label><label>P/E MAX<input id="stock-max-pe" type="number" min="0" step="0.1" value="${esc(filters.max_pe)}"></label><label>ROE MIN<input id="stock-min-roe" type="number" step="0.1" value="${esc(filters.min_roe)}"></label><label>ROE MAX<input id="stock-max-roe" type="number" step="0.1" value="${esc(filters.max_roe)}"></label><button id="stock-apply-filters" class="stock-page-btn" type="button">Apply Filters</button></div>${filters.sector?`<div class="stock-result-summary">${data.count||0} stocks match the current filters.</div><div class="stock-picker-list">${rows||`<div class="stock-no-data">No stocks match these filters.</div>`}</div>`:`<div class="stock-selection-instruction">Choose a sector first, then select a stock and refine the list using fundamental filters.</div>`}</section></div>`;
    screen.querySelector("#stock-apply-filters").addEventListener("click",()=>loadUniverse(screen));
    screen.querySelector("#stock-sector").addEventListener("change",()=>loadUniverse(screen));
    screen.querySelectorAll(".stock-select-btn").forEach(btn=>btn.addEventListener("click",()=>{const row=btn.closest(".stock-picker-row");selectedStock=(data.stocks||[]).find(s=>s.symbol===row.dataset.symbol)||null;renderSelection(data,screen);}));
    screen.querySelector("#stock-analyze-selected").addEventListener("click",()=>{if(selectedStock)showAnalysis(selectedStock.symbol);});
}
async function loadUniverse(screen) {
    screen.innerHTML=`<div class="stock-loading">Loading stock universe…</div>`;
    const params=new URLSearchParams(selectionFilters()); params.delete("sector"); const sector=document.getElementById("stock-sector")?.value; if(sector)params.set("sector",sector);
    try{const r=await fetch(`${API_BASE}/universe?${params.toString()}`,{headers:{Accept:"application/json"}});const data=await r.json();if(!r.ok)throw new Error(data?.detail||`HTTP ${r.status}`);renderSelection(data,screen);}catch(e){screen.innerHTML=`<div class="stock-error"><h2>Unable to load stock selection</h2><p>${esc(e.message)}</p><button class="stock-page-btn" id="stock-retry">Retry</button></div>`;screen.querySelector("#stock-retry").addEventListener("click",()=>loadUniverse(screen));}}
function showAnalysis(symbol) { const selection=document.getElementById("stock-selection-screen"), analysis=document.getElementById("stock-analysis-screen"), details=document.getElementById("stock-details"), status=document.getElementById("stock-analysis-status"); selection.hidden=true;analysis.hidden=false;window.history.pushState({},"",`?symbol=${encodeURIComponent(symbol)}`);loadStock(symbol,details,status); }
function showSelection() { document.getElementById("stock-analysis-screen").hidden=true;const selection=document.getElementById("stock-selection-screen");selection.hidden=false;window.history.pushState({},"",window.location.pathname);loadUniverse(selection); }

export function initStockAnalysis() {
    const selection=document.getElementById("stock-selection-screen"); const back=document.getElementById("stock-back-to-selection"); if(!selection)return;
    back?.addEventListener("click",showSelection); const params=new URLSearchParams(window.location.search); const symbol=(params.get("symbol")||"").trim().toUpperCase();
    window.addEventListener("popstate",()=>{const s=new URLSearchParams(window.location.search).get("symbol"); if(s)showAnalysis(s.toUpperCase()); else showSelection();});
    if(symbol)showAnalysis(symbol); else loadUniverse(selection);
}
